#!/bin/sh
# Start and stop youtube player.
#

RETVAL=0

sound_check() {
	if [ -d /sys/firmware/iopmodules -a -d /sys/bus/platform/drivers/ps2audio ]; then
		# Check if sound library was loaded.
		grep Sound_Device_Library /sys/firmware/iopmodules/*/name 2>/dev/null
		if [ $? -ne 0 ]; then
			# Load sound library
			echo "rom0:LIBSD" >/sys/firmware/iopmodules/load_module
			if [ $? -eq 0 ]; then
				# Load audio server
				echo "audsrv.irx" >/sys/firmware/iopmodules/load_module
				if [ $? -eq 0 ]; then
					# Activate audio driver
					echo "ps2audio.0" >/sys/bus/platform/drivers/ps2audio/bind
				fi
			fi
		fi
	fi
}

start() {
	echo "Checking sound"
	sound_check
	echo -n "Starting Juhutube services: "
	export HOME=/root
	youtubeplayer.sh &
	RETVAL=$?
	echo "done"

	return $RETVAL
}	

stop() {
	echo -n "Shutting down Juhutube services: "
	KILLPID=`pidof youtubeplayer.sh`
	if [ -n "$KILLPID" ]; then
		kill $KILLPID
	fi
	RETVAL=$?
	KILLPID=`pidof ytnavigator`
	if [ -n "$KILLPID" ]; then
		kill -9 $KILLPID
	fi
	KILLPID=`pidof ffplay`
	if [ -n "$KILLPID" ]; then
		kill $KILLPID
	fi
	echo "done"

	return $RETVAL
}	

restart() {
	stop
	sleep 2
	start
}	

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart|reload}"
	exit 1
esac

exit $?
